# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qdacc.ui'
#
# Created: Tue Mar 14 16:55:26 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(937, 768)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(280, 9, 651, 271))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.imageViewTop = GraphicsLayoutWidget(self.horizontalLayoutWidget_3)
        self.imageViewTop.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageViewTop.setObjectName(_fromUtf8("imageViewTop"))
        self.verticalLayout_2.addWidget(self.imageViewTop)
        self.imageViewBottom = GraphicsLayoutWidget(self.horizontalLayoutWidget_3)
        self.imageViewBottom.setObjectName(_fromUtf8("imageViewBottom"))
        self.verticalLayout_2.addWidget(self.imageViewBottom)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.mapViewCanvas = QtGui.QGraphicsView(self.horizontalLayoutWidget_3)
        self.mapViewCanvas.setObjectName(_fromUtf8("mapViewCanvas"))
        self.horizontalLayout_3.addWidget(self.mapViewCanvas)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 150, 261, 591))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.widget = QtGui.QWidget(self.groupBox_5)
        self.widget.setGeometry(QtCore.QRect(0, 30, 251, 481))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 30, 87, 101))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.speedControlP = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.speedControlP.setSingleStep(0.1)
        self.speedControlP.setObjectName(_fromUtf8("speedControlP"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.speedControlP)
        self.speedControlI = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.speedControlI.setSingleStep(0.1)
        self.speedControlI.setObjectName(_fromUtf8("speedControlI"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.speedControlI)
        self.speedControlD = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.speedControlD.setSingleStep(0.1)
        self.speedControlD.setObjectName(_fromUtf8("speedControlD"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.speedControlD)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 87, 101))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.balanceControlP = QtGui.QDoubleSpinBox(self.formLayoutWidget_3)
        self.balanceControlP.setSingleStep(0.1)
        self.balanceControlP.setObjectName(_fromUtf8("balanceControlP"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.balanceControlP)
        self.balanceControlI = QtGui.QDoubleSpinBox(self.formLayoutWidget_3)
        self.balanceControlI.setSingleStep(0.1)
        self.balanceControlI.setObjectName(_fromUtf8("balanceControlI"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.balanceControlI)
        self.balanceControlD = QtGui.QDoubleSpinBox(self.formLayoutWidget_3)
        self.balanceControlD.setSingleStep(0.1)
        self.balanceControlD.setObjectName(_fromUtf8("balanceControlD"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.balanceControlD)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 87, 101))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.positionControlP = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.positionControlP.setSingleStep(0.1)
        self.positionControlP.setObjectName(_fromUtf8("positionControlP"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.positionControlP)
        self.positionControlI = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.positionControlI.setSingleStep(0.1)
        self.positionControlI.setObjectName(_fromUtf8("positionControlI"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.positionControlI)
        self.positionControlD = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.positionControlD.setSingleStep(0.1)
        self.positionControlD.setObjectName(_fromUtf8("positionControlD"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.positionControlD)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.groupBox_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 30, 87, 101))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineFollowingControlP = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.lineFollowingControlP.setSingleStep(0.1)
        self.lineFollowingControlP.setObjectName(_fromUtf8("lineFollowingControlP"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineFollowingControlP)
        self.lineFollowingControlI = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.lineFollowingControlI.setSingleStep(0.1)
        self.lineFollowingControlI.setObjectName(_fromUtf8("lineFollowingControlI"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineFollowingControlI)
        self.lineFollowingControlD = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.lineFollowingControlD.setSingleStep(0.1)
        self.lineFollowingControlD.setObjectName(_fromUtf8("lineFollowingControlD"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineFollowingControlD)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.maxSpeedEdit = QtGui.QDoubleSpinBox(self.widget)
        self.maxSpeedEdit.setProperty("value", 0.5)
        self.maxSpeedEdit.setObjectName(_fromUtf8("maxSpeedEdit"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.maxSpeedEdit)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.maxAccelEdit = QtGui.QDoubleSpinBox(self.widget)
        self.maxAccelEdit.setProperty("value", 0.25)
        self.maxAccelEdit.setObjectName(_fromUtf8("maxAccelEdit"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.maxAccelEdit)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.maxTiltAngleEdit = QtGui.QDoubleSpinBox(self.widget)
        self.maxTiltAngleEdit.setProperty("value", 15.0)
        self.maxTiltAngleEdit.setObjectName(_fromUtf8("maxTiltAngleEdit"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.maxTiltAngleEdit)
        self.maxSteeringEdit = QtGui.QDoubleSpinBox(self.widget)
        self.maxSteeringEdit.setDecimals(1)
        self.maxSteeringEdit.setProperty("value", 10.0)
        self.maxSteeringEdit.setObjectName(_fromUtf8("maxSteeringEdit"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.maxSteeringEdit)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.updateBtn = QtGui.QPushButton(self.widget)
        self.updateBtn.setObjectName(_fromUtf8("updateBtn"))
        self.verticalLayout_3.addWidget(self.updateBtn)
        self.widget1 = QtGui.QWidget(self.groupBox_5)
        self.widget1.setGeometry(QtCore.QRect(0, 560, 251, 29))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.userCommandEdit = QtGui.QLineEdit(self.widget1)
        self.userCommandEdit.setObjectName(_fromUtf8("userCommandEdit"))
        self.horizontalLayout_4.addWidget(self.userCommandEdit)
        self.sendUserCommandBtn = QtGui.QPushButton(self.widget1)
        self.sendUserCommandBtn.setObjectName(_fromUtf8("sendUserCommandBtn"))
        self.horizontalLayout_4.addWidget(self.sendUserCommandBtn)
        self.widget2 = QtGui.QWidget(self.groupBox_5)
        self.widget2.setGeometry(QtCore.QRect(0, 520, 251, 29))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.formLayout_6 = QtGui.QFormLayout(self.widget2)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_19 = QtGui.QLabel(self.widget2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.updateRateEdit = QtGui.QDoubleSpinBox(self.widget2)
        self.updateRateEdit.setProperty("value", 0.1)
        self.updateRateEdit.setObjectName(_fromUtf8("updateRateEdit"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.updateRateEdit)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 261, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 251, 99))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hostAddressEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.hostAddressEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hostAddressEdit.setObjectName(_fromUtf8("hostAddressEdit"))
        self.horizontalLayout_2.addWidget(self.hostAddressEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.portEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.portEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.portEdit.setObjectName(_fromUtf8("portEdit"))
        self.horizontalLayout.addWidget(self.portEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.connectBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.connectBtn.setObjectName(_fromUtf8("connectBtn"))
        self.verticalLayout.addWidget(self.connectBtn)
        self.widget3 = QtGui.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(280, 290, 651, 451))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.gridLayout = QtGui.QGridLayout(self.widget3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plot_ll = PlotWidget(self.widget3)
        self.plot_ll.setObjectName(_fromUtf8("plot_ll"))
        self.gridLayout.addWidget(self.plot_ll, 2, 0, 1, 1)
        self.plot_ul = PlotWidget(self.widget3)
        self.plot_ul.setObjectName(_fromUtf8("plot_ul"))
        self.gridLayout.addWidget(self.plot_ul, 0, 0, 1, 1)
        self.plot_ur = PlotWidget(self.widget3)
        self.plot_ur.setObjectName(_fromUtf8("plot_ur"))
        self.gridLayout.addWidget(self.plot_ur, 0, 1, 1, 1)
        self.plot_lr = PlotWidget(self.widget3)
        self.plot_lr.setObjectName(_fromUtf8("plot_lr"))
        self.gridLayout.addWidget(self.plot_lr, 2, 1, 1, 1)
        self.plot_lr_select_combo = QtGui.QComboBox(self.widget3)
        self.plot_lr_select_combo.setObjectName(_fromUtf8("plot_lr_select_combo"))
        self.gridLayout.addWidget(self.plot_lr_select_combo, 3, 1, 1, 1)
        self.plot_ll_select_combo = QtGui.QComboBox(self.widget3)
        self.plot_ll_select_combo.setObjectName(_fromUtf8("plot_ll_select_combo"))
        self.gridLayout.addWidget(self.plot_ll_select_combo, 3, 0, 1, 1)
        self.plot_ul_select_combo = QtGui.QComboBox(self.widget3)
        self.plot_ul_select_combo.setObjectName(_fromUtf8("plot_ul_select_combo"))
        self.gridLayout.addWidget(self.plot_ul_select_combo, 1, 0, 1, 1)
        self.plot_ur_select_combo = QtGui.QComboBox(self.widget3)
        self.plot_ur_select_combo.setObjectName(_fromUtf8("plot_ur_select_combo"))
        self.gridLayout.addWidget(self.plot_ur_select_combo, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QRobot Debug and Control Center", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Robot Parameters", None))
        self.groupBox.setTitle(_translate("MainWindow", "Speed Control", None))
        self.label_3.setText(_translate("MainWindow", "P", None))
        self.label_4.setText(_translate("MainWindow", "I", None))
        self.label_5.setText(_translate("MainWindow", "D", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Balance Control", None))
        self.label_9.setText(_translate("MainWindow", "P", None))
        self.label_10.setText(_translate("MainWindow", "I", None))
        self.label_11.setText(_translate("MainWindow", "D", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Position Control", None))
        self.label_6.setText(_translate("MainWindow", "P", None))
        self.label_7.setText(_translate("MainWindow", "I", None))
        self.label_8.setText(_translate("MainWindow", "D", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Line Following", None))
        self.label_12.setText(_translate("MainWindow", "P", None))
        self.label_13.setText(_translate("MainWindow", "I", None))
        self.label_14.setText(_translate("MainWindow", "D", None))
        self.label_16.setText(_translate("MainWindow", "Max Accel (m/s^2)", None))
        self.label_15.setText(_translate("MainWindow", "Max Speed (m/s)", None))
        self.label_17.setText(_translate("MainWindow", "Max Tilt Angle (deg)", None))
        self.label_18.setText(_translate("MainWindow", "Max Steering Input", None))
        self.maxSteeringEdit.setToolTip(_translate("MainWindow", "Maximum steering control output.  (1 to 20)", None))
        self.updateBtn.setText(_translate("MainWindow", "Update", None))
        self.sendUserCommandBtn.setText(_translate("MainWindow", "Send", None))
        self.label_19.setText(_translate("MainWindow", "Debug Update Rate (sec)", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Connection Parameters", None))
        self.label_2.setText(_translate("MainWindow", "Host Address:", None))
        self.hostAddressEdit.setText(_translate("MainWindow", "10.10.4.127", None))
        self.label.setText(_translate("MainWindow", "Port:", None))
        self.portEdit.setText(_translate("MainWindow", "9000", None))
        self.connectBtn.setText(_translate("MainWindow", "Connect", None))

from pyqtgraph import GraphicsLayoutWidget, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

